# Generated by Django 2.2 on 2024-11-16 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='division',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
