# Generated by Django 2.2 on 2024-11-17 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_remove_order_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='transaction_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='division',
            field=models.CharField(max_length=20),
        ),
    ]
